baseURL: "https://jeffdev7.github.io/static-website/"
theme: "up-business-theme"
languageCode: "en-us"
canonifyURLs: true
title: "Jago"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Jago Desenvolvimento de Soluções"
  description: "Somos especialistas em desenvolvimento e manutenção de soluções Web."
  images: 
    - "images/hero-image.png"

  logo: "logo-jago.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "##1c1c1c"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"
    twitter: "#"

  contact:
    - "jago.websolutions@gmail.com"
    - "+55 11 98xxx-xxxx"

  copyright: "© 2024 Jago Desenvolvimento de Soluções"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

  buttons:
    - name: "How we work"
      url: "/#"
      weight: 2
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

taxonomies:
  series: "series"
  tags: "tags"
